version: '3.4'

services:
  library-api:
    image: library-api:latest
    container_name: library-api
    restart: always
    build:
      context: ../../
      dockerfile: src/Library.API/Dockerfile
    ports:
      - "7070:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__LibraryConnection=Server=library-api-db,1433;Database=LibraryCompose;User ID=sa;Password=1q2w3e4r@DO;Trusted_Connection=False; TrustServerCertificate=True;
      - RabbitMQ__HostName=library-api-rabbit
      - RabbitMQ__UserName=library
      - RabbitMQ__Password=Rabbit!@#
    depends_on:
      - library-api-db
      - library-api-rabbit
  
  library-api-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: library-api-db
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "1q2w3e4r@DO"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      
  library-api-db-mssqltools:
    image: mcr.microsoft.com/mssql-tools
    container_name: library-api-db-mssqltools
    depends_on:
      - library-api-db
    volumes:
      - ./scripts/00-Library.sql:/tmp/00-Library.sql
      - ./scripts/01-Library.sql:/tmp/01-Library.sql
      - ./scripts/init-Library.sh:/tmp/init-Library.sh
    command: /bin/bash ./tmp/init-Library.sh     

  library-api-rabbit:
    image: rabbitmq:3-management
    container_name: library-api-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "library"
      RABBITMQ_DEFAULT_PASS: "Rabbit!@#"
    
    